name: ZachLarmer
favicon: null
layout_spectrum: 0.65
typography_spectrum: 0.59622
title: Zach Larmer - Musician
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.9169809406157583
  saturation: 0.024407067336142063
  rhythmicContrast: 0.5
purpose: []
