name: ZachLarmer
favicon: null
layout_spectrum: 0.7151648185681552
typography_spectrum: 0.36563952057622373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3765698408242315
  lightness: 0.9169809406157583
  saturation: 0.024407067336142063
  rhythmicContrast: 0.09502048697322607
purpose: []
